services:
  - type: web
    name: aipromptdoc-api
    runtime: python
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aipromptdoc-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.0
    healthCheckPath: /health

databases:
  - name: aipromptdoc-db
    databaseName: aipromptdoc
    user: aipromptdoc
    plan: free

